# Generated by Django 5.2.10 on 2026-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='medications',
            field=models.TextField(blank=True, help_text='Comma separated medications'),
        ),
        migrations.AddField(
            model_name='disease',
            name='remedies',
            field=models.TextField(blank=True, help_text='Comma separated remedies'),
        ),
    ]
